# Generated by Django 5.0.14 on 2026-06-24 13:33

from django.db import migrations, models
from django.conf import settings

if settings.DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    from django.contrib.postgres.fields import ArrayField
    from django.contrib.postgres.indexes import GinIndex
    tags_field = ArrayField(models.CharField(max_length=50), default=list)
    meta_indexes = [
        GinIndex(fields=['tags'], name='product_tags_gin'),
    ]
else:
    tags_field = models.JSONField(default=list)
    meta_indexes = []

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(db_index=True, max_length=255)),
                ("product_description", models.TextField()),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("tags", tags_field),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": meta_indexes,
            }
        ),
    ]
